/*
	This file contains the common constants for indexer
*/
package constants

//Request params
const (
	UserAgent     = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
	DatabaseIndex = "mails"
	IndexSchema   = `
	{
		"name":"mails",
		"shard_num":3,
		"storage_type":"disk",
		"mappings":{
		   "properties":{
			  "Content":{
				 "type":"text",
				 "index":true,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "ContentTransferEconding":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "ContentType":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "Date":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "From":{
				 "type":"text",
				 "index":true,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "MessageId":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "MimeVersion":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "Subject":{
				 "type":"text",
				 "index":true,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "To":{
				 "type":"text",
				 "index":true,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "XBCC":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "XCC":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "XFilename":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "XFolder":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "XFrom":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "XOrigin":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  },
			  "XTo":{
				 "type":"text",
				 "index":false,
				 "store":false,
				 "sortable":false,
				 "aggregatable":false,
				 "highlightable":false
			  }
		   }
		}
	 }
	`
)
